### PR TITLE
Enhanced electric and magnetic field transport

### PR DESCRIPTION
**Pull request by victorMalkov**
- Null definitions to egsnrc.macros for no-field simulations
- EEMF macros added as two files. One for general simulations and one to work with BEAMnrc (required due to the way howfar and hownear are defined in BEAM).
- Changes to egsnrc.mortran to include the EEMF effects. The macros for the original macros can still be used as well.
- Electric field transport has not been fully tested and varified. Caution should be used, particularly if using changing electric fields.
- Spatially varying fields are not explicitly supported. Small step sizes would allow for some spattial differences in the field.

### CODE REVIEW

**Comment by Cukhen** [comment]
I can't compile egs_chamber with this:

`Mortran compiling EGSnrc sources ...
gfortran -O3 -ffast-math -fPIC    -c -o egsnrc_linux64.o egsnrc_linux64.F
egsnrc_linux64.F:11634.27:

      COMMON/EM/  B_amp, Bx, By, Bz, E_amp, Ex, Ey, Ez, beta_em,  beta_e
                           1
Error: Symbol 'bx' at (1) is already in a COMMON block
egsnrc_linux64.F:11671.22:

      real*8 B_amp, Bx, By, Bz,
                      1
Error: Symbol 'bx' at (1) already has basic type of REAL
egsnrc_linux64.F:17390.27:

      COMMON/EM/  B_amp, Bx, By, Bz, E_amp, Ex, Ey, Ez, beta_em,  beta_e
                           1
Error: Symbol 'bx' at (1) is already in a COMMON block
egsnrc_linux64.F:17427.22:

      real*8 B_amp, Bx, By, Bz,
                      1
Error: Symbol 'bx' at (1) already has basic type of REAL
egsnrc_linux64.F:18025.27:

      COMMON/EM/  B_amp, Bx, By, Bz, E_amp, Ex, Ey, Ez, beta_em,  beta_e
                           1
Error: Symbol 'bx' at (1) is already in a COMMON block
egsnrc_linux64.F:18062.22:

      real*8 B_amp, Bx, By, Bz,
                      1
Error: Symbol 'bx' at (1) already has basic type of REAL
egsnrc_linux64.F:12800.40:

                                alpha_em = omega_em*1e-3/(100.0*v_i)
                                        1
Error: Symbol 'alpha_em' at (1) has no IMPLICIT type
egsnrc_linux64.F:11790.19:

              B_amp = 0.
                   1
Error: Symbol 'b_amp' at (1) has no IMPLICIT type
egsnrc_linux64.F:11834.21:

              beta_em = sqrt(1-(0.510998910/E_total)**2)
                     1
Error: Symbol 'beta_em' at (1) has no IMPLICIT type
egsnrc_linux64.F:11836.22:

              beta_em2 = beta_em**2
                      1
Error: Symbol 'beta_em2' at (1) has no IMPLICIT type
egsnrc_linux64.F:11837.17:

              Bvi = v_i*B_amp
                 1
Error: Symbol 'bvi' at (1) has no IMPLICIT type
egsnrc_linux64.F:12802.37:

                                cos_a = cos(alpha_em)
                                     1
Error: Symbol 'cos_a' at (1) has no IMPLICIT type
egsnrc_linux64.F:12589.31:

                          de_EM =0.
                               1
Error: Symbol 'de_em' at (1) has no IMPLICIT type
egsnrc_linux64.F:11791.21:

              delta_u = 0.02
                     1
Error: Symbol 'delta_u' at (1) has no IMPLICIT type
egsnrc_linux64.F:11920.37:

                    duAdaptivEMFactor = (1.5/B_amp)**(1./5.)
                                     1
Error: Symbol 'duadaptivemfactor' at (1) has no IMPLICIT type
egsnrc_linux64.F:11795.19:

              E_amp = 0.
                   1
Error: Symbol 'e_amp' at (1) has no IMPLICIT type
egsnrc_linux64.F:11833.21:

              E_total = eke + 0.510998910
                     1
Error: Symbol 'e_total' at (1) has no IMPLICIT type
egsnrc_linux64.F:11856.26:

                eloss_corr=0.5*(1+v_i/v_f)
                          1
Error: Symbol 'eloss_corr' at (1) has no IMPLICIT type
egsnrc_linux64.F:11844.22:

              EM_const=1.0
                      1
Error: Symbol 'em_const' at (1) has no IMPLICIT type
egsnrc_linux64.F:13159.27:

                  EM_const0 = vstep
                           1
Error: Symbol 'em_const0' at (1) has no IMPLICIT type
egsnrc_linux64.F:11792.16:

              Ex = 0.
                1
Error: Symbol 'ex' at (1) has no IMPLICIT type
egsnrc_linux64.F:11793.16:

              Ey = 0.
                1
Error: Symbol 'ey' at (1) has no IMPLICIT type
egsnrc_linux64.F:11794.16:

              Ez = 0.
                1
Error: Symbol 'ez' at (1) has no IMPLICIT type
egsnrc_linux64.F:12655.34:

                          omega_em = abs(B_amp*299792458.0*299792458.0*1
                                  1
Error: Symbol 'omega_em' at (1) has no IMPLICIT type
egsnrc_linux64.F:13138.24:

                  r02_em = sqrt( u_perp*u_perp + v_perp*v_perp + w_perp*
                        1
Error: Symbol 'r02_em' at (1) has no IMPLICIT type
Fatal Error: Error count reached limit of 25.
`

**Comment by victorMalkov** [comment]
Thank you for catching this @Cukhen ! It seems that definitions for the Bx, By, and Bz had been added since I was using the older magnetic field transport. For the time being I commented out the definition of these variables in my additions so that both the existing magnetic field transport and the new one can be used.

**Comment by ftessier** [comment]
@victorMalkov, does this pull request supersede #211 entirely?

**Comment by ftessier** [comment]
Just rebased the branch on current `develop` in view of merging this soon.

**Comment by ftessier** [comment]
This pull request has been integrated in the pull request #211.

**Pull request closed without merging**
