### PR TITLE
Add radionuclide source refinements (collimated source, experiment time ...)

### PR DESCRIPTION
**Pull request by rtownson**
A number of radionuclide source refinements.

1. Adds the option for a collimated radionuclide source. This is done by setting `source type = collimated` in the radionuclide source block.

2. Reduces the scope of radionuclide source specific methods, instead of declaring them at the base source and spectrum levels. The radionuclide source now statically casts the spectrum to a radionuclide spectrum in order to access the special methods, and applications should do the same to access the radionuclide source methods.

3. Adds an `experiment time` parameter to the radionuclide source, so that emissions can be restricted according to their emission times. These emissions that would be outside the measurement time get returned by the source as zero energy particles.

4. Adds a method to query the type of radionuclide emission that just occurred. For example, what type of disintegration occurred (beta/alpha/EC) and/or what type of particle was returned (IT photon, fluorescent photon, Auger electron).

### CODE REVIEW

**Comment by rtownson** [comment]
I added some extra comments in the doxygen to warn the user of the collimated source drawbacks.

**Comment by rtownson** [comment]
I'm done working on this PR now and have updated the description accordingly.

**Comment by rtownson** [comment]
Now that I added back in the `getMu()` function that I had removed by accident, yes it is ready.

**Comment by ftessier** [comment]
@rtownson this was my fault, sorry: git raised a conflict when I rebased, but I missed the vanishing of `getMu()` in the diff! I will clean that up, thanks for the commit.

**Comment by ftessier** [comment]
Squashed the fix commit (and checked that `git diff` is clean compared to the original rebased on `develop`, and resolving the conflict in `egs_base_source.h` this time!)

**Comment by ftessier** [comment]
@blakewalters please review when you have a chance. Thanks!

**Comment by ftessier** [comment]
Fix typo in commit message, and remove update merge before merging into `develop`

**Pull request merged**
