### PR TITLE
Typos in DOSXYZnrc usage

### PR DESCRIPTION
**Pull request by hdclark**
Fixed a few small typos and formatting inconsistencies in the DOSXYZnrc usage print-out.

### CODE REVIEW

**Comment by rtownson** [comment]
Thanks for these fixes! 

For future pull requests the usual method is to (1) `git checkout develop` (2) create a new branch based on develop (`git branch -b myBranch`) (3) make a pull request from that branch. Then we merge changes into the develop branch instead of master.

@ftessier I changed the base branch to develop instead of master, can you rebase on develop to fix the mess of commits this created?

**Comment by hdclark** [comment]
Will do. Thanks.

**Comment by ftessier** [comment]
Thank you @hdclark! I will rebase your master branch on develop, add your commit and force push the changes to your master branch, in order to be able to fold in your pull request.

**Comment by ftessier** [comment]
@hdclark I don't have permission to push to your master branch. I will thus push changes to a new branch on our repository and open a new pull request to replace this one.

**Comment by ftessier** [comment]
Replaced by pull request #431.

**Pull request closed without merging**
