### PR TITLE
Configuration and documentation for building and running in Codespaces or Development Container

### PR DESCRIPTION
**Pull request by markphip**
This adds the configuration necessary to build and run EGSnrc in a Development Container. I have
successfully tested this in the following environments:

- [x] GitHub Codespaces
- [x] MacOS using VS Code and Docker Desktop (requires #1100)
- [x] Windows using VS Code and Docker Desktop with WSL2 backend

Documentation:

* [`.devcontainer/README.md`](diffhunk://#diff-0f9548cbce10dbdef0b86d783ed0727a4ac1061fc71cb549b5dbd400705c71fdR1-R92): A new README file has been added to explain how to use the development container. It provides instructions for different environments and addresses potential issues, such as line-endings in files when running locally on Windows. It also describes the runtime experience and provides reference information.

Development container configuration:

* [`.devcontainer/devcontainer.json`](diffhunk://#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686R1-R19): This file contains the configuration for the development container. It specifies the Docker image to use, features to include, commands to run on creation and after creation, ports to forward, and attributes for the forwarded ports.

Scripts for container setup and GUI applications build:
* [`.devcontainer/setup.sh`](diffhunk://#diff-aaf9e7764a12876cbe70d492c719e21e8590390a38d0f037193a765df858fdbfR1-R19): This script runs when the development container is being created. It installs the required packages for EGSnrc, builds the application, and configures `.bashrc` with necessary environment variables and source commands.
* [`.devcontainer/build-gui-apps.sh`](diffhunk://#diff-ff1a12467853dd338a68fd2eaf713d9f23a947099a0c6c043fe0925bc43f13e7R1-R14): This script is used to build the GUI applications for EGSnrc. It checks if the `EGS_HOME` environment variable is set and sources `~/.bashrc` if not. It then builds the GUI applications.

### CODE REVIEW

**Comment by mainegra** [comment]
This is a very timely contribution! 
It will definitively make it easier for users to use EGSnrc in their preferred OS on any machine regardless of the host OS!

**Review by rtownson — APPROVED** [review]
For unrelated reasons I couldn't get docker running on my Windows work laptop, so I haven't tested this properly yet. I'm still fine with including this PR though, since it won't impact anything else.

**Comment by ftessier** [comment]
Yes, let's add it and then we and others can play with it and improve!

**Comment by ftessier** [comment]
@markphip quick question: is the `.devcontainer` directory name canonical, or can it be anything?

**Comment by markphip** [comment]
@ftessier The specification describes a limited number of names and folders for the configuration. See https://containers.dev/implementors/spec/#devcontainerjson

**Review by ftessier — APPROVED** [review]

**Review by mainegra — APPROVED** [review]

**Comment by rtownson** [comment]
Added new lines to the ends of the scripts.

**Pull request merged**
