### PR TITLE
Feature expand environment variable in file names for C++ apps

### PR DESCRIPTION
**Pull request by mainegra**
Introduces the C++ EGSnrc global function `egsExpandPath` to search for _**one**_ environment variable _anywhere_ in the string argument and expand it with its value. It understands Unix (`$VAR`) and Windows (`%VAR%`) environment variables, as well as their file separators (backslash or slash). However the file name is output using slashes as file separators. Consequently:

- Spectrum file names can now include an environment variable such as `$EGS_HOME` or `$HEN_HOUSE`
- C++ apps requesting input of a file name were updated to use this feature
- egs++ spectrum file names can also use environment variables

This feature matches the functionality already existing for Mortran apps although with added flexibility.

### CODE REVIEW

**Comment by mainegra** [comment]
@ftessier I don't know why [this commit](https://github.com/nrc-cnrc/EGSnrc/pull/600/commits/7cd9622f34adf3f449c1884d8b74748c7b8b2d3c) got included in this branch, but probably because of my lack of experience with pulling and rebasing. Could you see if you can get rid of it?

**Comment by ftessier** [comment]
Rebased on `develop` and applied astyle formatting.

**Comment by ftessier** [comment]
Travis seems down, but I have checked locally that compilation is successful.

**Comment by ftessier** [comment]
Can't merge until Travis completes. Will do then.

**Comment by ftessier** [comment]
Rebased on `develop` and fixed merge conflicts in `egs_kerma` files.

**Pull request merged**
