### PR TITLE
Fix BEAMnrc synchdmlc component module bugs

### PR DESCRIPTION
**Pull request by blakewalters**
Fixed many small bugs in transport through leaf cross-sections.  Some of these were introduced with the override of some cross-section dimensions necessary to accurately model the 120MLC and HD120 collimators back in 2018.  However, some of these bugs predate that change.  

This PR also includes new leaf orientation options for SYNCHDMLC, ORIENT=2,3, which automatically reflect leaves about the axis perpendicular to the leaf opening direction so that the MLC coordinate system matches that in the manufacturer (Varian) specs for 120MLC and HD120.  This reflection reverses the order of leaf numbering, and so leaf opening sequences are automatically "flipped" so that the opening coordinate applied to leaf i is instead applied to leaf N-i+1, where N is the total no. of leaves.  See the updated BEAMnrc manual for more details.

Many thanks to Dr. Jarkko Ojala without whose collaboration these fixes and enhancements would not have been possible.

### CODE REVIEW

**Comment by ftessier** [comment]
@blakewalters this series of commits also include the radiative splitting ausgab object. Let me know if this is intentional, and I will split the pull request between synchdmlc and the ausgab object.

**Comment by ftessier** [comment]
@blakewalters Oh I see, you already removed the changes related to radiative splitting in later commits...

**Comment by ftessier** [comment]
Extracted the ausgab object radiative splitting commits from this pull request branch, and put them on a new branch `feature-radiative-splitting`.

**Comment by ftessier** [comment]
Rebased on develop.

**Comment by ftessier** [comment]
Adjusted commit messages, squashed some commits together. Verified that there is no diff with the original pull request head.

**Comment by ftessier** [comment]
Squashed a couple more commits, tweaked messages. Verified that there is no diff with the original pull request head.

**Review by ftessier — APPROVED** [review]

**Comment by ftessier** [comment]
Removed EOL whitespace in files modified by the pull request. No diff apart from whitespace, as confirmed with `git diff -w`

**Comment by ftessier** [comment]
@blakewalters please confirm that you are ok with the cleaned up branch. @rtownson amd @mainegra please review when you get a change.

**Comment by blakewalters** [comment]
Looks good, @ftessier!  Thanks for cleaning it up.

**Review by rtownson — APPROVED** [review]

**Review by mainegra — APPROVED** [review]

**Pull request merged**
