### PR TITLE
Add 3ddose_tools repo to EGSnrc's HEN_HOUSE/gui

### PR DESCRIPTION
**Pull request by MartinMartinov**
Reformatted 3ddose_tools from online repository
https://github.com/MartinMartinov/3ddose_tools for integration with
EGSnrc.

### CODE REVIEW

**Comment by ftessier** [comment]
@MartinMartinov can I include this as a submodule? Then, you can continue to maintain it on your account, and we would just be _consuming_ 3ddose_tools within EGSnrc. I think I will create a "third-party" directory in EGSnrc (name it `coop`, as in chicken coop?), to insert other repos as submodules. What do you think?

**Comment by MartinMartinov** [comment]
It sounds like a great plan, and a lot easier for me to manage.  Coop is a great name, fits right in on with the egs pun pantry :)

**Comment by ftessier** [comment]
@MartinMartinov heads up, planning to add this as a submodule for this year's release. :-)

**Review by mainegra — APPROVED** [review]

**Comment by ftessier** [comment]
Superseded by #906.

**Pull request closed without merging**
