### PR TITLE
Fix loop index compiler warning in egs_cylinders/egs_cylinders.h

### PR DESCRIPTION
**Pull request by mxxo**
Fixes the lone loop index compiler warning for egs++

### CODE REVIEW

**Comment by ftessier** [comment]
I changed the target branch to `small-stuff`, which gets all squashed and merged into develop ahead of the release.

**Comment by mxxo** [comment]
Of course @ftessier, thank you for letting me know :)

**Comment by mxxo** [comment]
Just rebased onto `small-stuff`

**Review by rtownson — APPROVED** [review]

**Review by ftessier — APPROVED** [review]

**Review by mainegra — APPROVED** [review]

**Comment by ftessier** [comment]
Note: I had merged this without noticing that the commit title had to be adjusted to follow our [guidelines](https://github.com/nrc-cnrc/EGSnrc/wiki/Git-commit-messages). I adjusted it after the fact on the `small-stuff` branch directly. @mxxo you might want to delete your `compiler-warning` branch to ensure you don't base future work on the stale commit.

**Comment by mxxo** [comment]
Thank you @ftessier, I'll make sure to follow the guidelines going forward :)

**Comment by ftessier** [comment]
No worries, I usually look after _implementing_ these guidelines... 😄  They help with some of the automated tools out there, including github. For example, the 50 char limit on commit title is often assumed by git tools for formatting, and the "Fix #xxx:" prefix in commit titles on github closes issues automatically (when merged to the main project branch), etc.

**Pull request merged**
