### PR TITLE
Fix #1018: Number of brems events miscounted for DBS in BEAMnrc

### LINKED ISSUE #1018: Bremsstrahlung number of events egslst message miscounts for DBS in BEAMnrc
### Discussed in https://github.com/nrc-cnrc/EGSnrc/discussions/1015

<div type='discussions-op-text'>

<sup>Originally posted by **piliop1** June 16, 2023</sup>
I use EGSnrc for KV energies (125KV).
When I use ‘UBS’ and ‘None’ Bremsstrahlung splitting, I can see in the report (.egslst file)  that Bremsstrahlung events are present.
Using beamdp to list the particles in the phase space file I can see that we do have bremsstrahlung photons because LATCH BIT 0 is set to 1 for those photons.
Whenever I set Directional Bremsstrahlung splitting, I notice in the report (.egslst file) that the number of Bremsstrahlung events is ZERO!!! (I tried a plenty of parameter combinations for splitting field radius, SSD and Bremsstrahlung Splitting Number but no success).
Using again beamdp to list the generated particles I can see that Bremsstrahlung photons are present because of LATCH’s BIT0 set to 1.
Can please somebody explain this behavior? How is it possible to get Bremsstrahlung photons without Bremsstrahlung events?
Thank you!
</div>

### PR DESCRIPTION
**Pull request by rtownson**
Fix the output message in the egslst file for BEAMnrc simulations about the number of brems events the took place. When DBS was turned on, it would always read zero.

Just to be clear, there was nothing wrong with the splitting or the simulation. This is just a small bug in the counter variable that is only used to print to the egslst file.

@blakewalters please double check this change.

### CODE REVIEW

**Review by ftessier — APPROVED** [review]

**Comment by ftessier** [comment]
@blakewalters please double-check this pull request for merging.

**Comment by ftessier** [comment]
- [x] Checked that `NUM_BREM` is only ever used for [information output](https://github.com/nrc-cnrc/EGSnrc/blob/e4044c1210fbbf169ee62a9452c7e176ad5367b1/HEN_HOUSE/omega/beamnrc/beamnrc.mortran#L8994-L8996), and nothing else

**Review by mainegra — APPROVED** [review]

**Comment by blakewalters** [comment]
@rtownson: Please see my question above about possible miscounts when BCSE is used.

**Comment by rtownson** [comment]
> @rtownson: Please see my question above about possible miscounts when BCSE is used. Thanks!

I'm not seeing this question, could you give a link?

**Comment by blakewalters** [comment]
@rtownson: See the comment in https://github.com/nrc-cnrc/EGSnrc/pull/1019/files

**Comment by rtownson** [comment]
> @rtownson: See the comment in https://github.com/nrc-cnrc/EGSnrc/pull/1019/files

@blakewalters strange, there's no comment there for me.. I guess just repeat it here!

**Comment by ftessier** [comment]
@blakewalters there is no comment, but you might see it if you have not clicked on "submit single comment" (or "start a review). If the comment does not show up in the conversation thread, then it has not been registered, so to speak.

**Comment by rtownson** [comment]
Thanks for catching that Blake, I've fixed it as per your suggestion so it will work for BCSE as well.

**Comment by ftessier** [comment]
Great catch @blakewalters 🏅!

**Review by blakewalters — APPROVED** [review]

**Pull request merged**
