### PR TITLE
Fix for radiative Compton correction check

### PR DESCRIPTION
**Pull request by mainegra**
According to issue #64 file `rad_compton1.mortran` has to be placed just before `get_inputs.mortran` to pass the check of whether the file was included or not in the compilation process. However, the EGSnrc manual PIRS-701 states that `rad_compton1.mortran` can be placed just before egsnrc.mortran which is not correct as currently implemented. Several issues are fixed in this pull request:

1. Typo in warning message reported `rad_compton.mortran` was needed rather than `rad_compton1.mortran`.
2. Check removed from `get_inputs.mortran` as it was printing a message that disrupted the output format of the MC transport parameters requested by the user.
3. Now the check is actually done during the HATCH step. As a consequence one can now place `rad_compton1.mortran` anywhere between `egsnrc.macros` and `egsnrc.mortran` in the application's Makefile.

### CODE REVIEW

**Comment by ftessier** [comment]
Do you want to fix PIRS-701 accordingly?

**Comment by mainegra** [comment]
We could be more specific and say that `radc_compton1.mortran` can be placed anywhere between egsnrc.macros and egsnrc.mortran in the Makefile. But as it is now it is correct. More important will be to explain how to add this file for different type of applications (MORTRAN, C++).

**Comment by ftessier** [comment]
@mainegra, I tried the fix, and although it seems to turn Radiative corrections OFF if I don't include the `radc_compton1.mortran` file, in the `Electron/Photon transport parameter` output in `.egslog` it still reports that is is ON (see below). Can this be fixed easily?

```

***************** Warning: 
 You are trying to use radiative Compton corrections
 without having included rad_compton1.mortran
Turning radiative Compton corrections OFF ...


 Bound Compton scattering not requested! 

  EGSnrc SUCCESSFULLY 'HATCHED' FOR ONE MEDIUM.

================================================================================

                   Electron/Photon transport parameter

================================================================================

 Photon cross sections                                      xcom
 Compton cross sections                                     default
 Photon transport cutoff(MeV)                                    0.1000E-01
 Pair angular sampling                                       SIM
 Pair cross sections                                         BH 
 Triplet production                                          Off
 Bound Compton scattering                                    OFF           
 Radiative Compton corrections                               ON            
 Rayleigh scattering                                         OFF           
 Atomic relaxations                                          OFF           
 Photoelectron angular sampling                              OFF           

 Electron transport cutoff(MeV)                               0.7000
 Bremsstrahlung cross sections                              BH  
 Bremsstrahlung angular sampling                             SIM
 Spin effects                                                On
 Electron Impact Ionization                                  Off
 Maxium electron step in cm (SMAX)                                5.000    
 Maximum fractional energy loss/step (ESTEPE)                0.2500
 Maximum 1st elastic moment/step (XIMAX)                     0.5000
 Boundary crossing algorithm                                 PRESTA-I  
 Skin-depth for boundary crossing (MFP)                      330.8    
 Electron-step algorithm                                     PRESTA-II 

================================================================================
```

**Comment by mainegra** [comment]
@ftessier this is the expected behavior from my fix. I want to keep the output for the `Electron/Photon transport parameter` faithful to the user's input and then warn that the source file required is not available and hence this option will be turned off. Another problem with updating the output message in the `Electron/Photon transport parameter` is that it will force the use of the macro $RADC_WARNING in `get_inputs.mortran` and force placing `radc_compton1.mortran` just before `get_inputs.mortran` in the Makefile.

**Comment by ftessier** [comment]
Ok, understood, let's leave it like that then, however misleading it may be.

**Comment by ftessier** [comment]
Disruptive to the output format, I agree, but less likely to be missed.

**Comment by mainegra** [comment]
Reverted back to checking in `get_inputs.mortran` since as @ftessier commented above it would be misleading for the user. Now file `radc_compton1.mortran` **MUST** be included before `get_inputs.mortran` in the Makefile as suggested in issue #64. Now the check is done before creating the output strings hence the output block `Electron/Photon transport parameter` correctly shows the radiative Compton corrections to be turned OFF. The EGSnrc manual PIRS-701 needs to reflect this!

**Comment by ftessier** [comment]
Also adjust the comment in the header in `radc_compton1.mortran`:
```                                                                             "
"  - add this file to the list of files needed to build EGSnrc just before    "
"    $(EGS_SOURCEDIR)egsnrc.mortran 
```

**Comment by mainegra** [comment]
It is not misleading anymore with the latest commit!

**Pull request merged**
