### PR TITLE
Fix source collection and simple alias table

### PR DESCRIPTION
**Pull request by rtownson**
1. Fixed phsp support in the `egs_source_collection`, that was due to not defining `setSimulationChunk`. It has been added to match what already exists in `egs_transformed_source`. The bug meant that parallel runs using phase-spaces in a source collection would not have the parallel "chunks" starting at different locations in the phsp. Instead, all chunks would start at the beginning of the phsp, effectively resulting in extra recycling of those particles. In highly parallel or low number of particle simulations, this would affect the statistics and potentially introduce latent phase-space variance artifacts.

2. Fixed a bug in `EGS_SimpleAliasTable` where certain series of weights did not result in correct sampling. For example, using weight = 10 10 1 1 in a source collection resulted in sampling of 10:5.5:1:5.5 instead of 10:10:1:1. The incorrect weighting was triggered only in a relatively rare combination dependent on the order of weights, their values and their sum. Fred describes the solution in the comments below.

`EGS_SimpleAliasTable` is used in `egs_source_collection`, `egs_voxelized_shape`, `egs_shape_collection` and `egs_atomic_relaxations`.

Thanks to Patty Oliver for reporting these issues.

### CODE REVIEW

**Comment by ftessier** [comment]
@rtownson can I remove the debugging code which is commented out?

**Comment by rtownson** [comment]
@ftessier you are welcome to remove it - I just left it in case this is a debug test we might want to do in the future.

**Comment by ftessier** [comment]
I don't agree with the previous fix. It solves the sample failure case (10, 10, 1, 1), but this is coincidental and the code remains fragile, because the there is no distinction between failing to find a high (or low) bin, and exhausting the corresponding loop. Therefore extraneous aliasing might be performed, despite all bins being already equalized. In the failure case this triggers an aliasing of the last bin with itself, with biased results. I patched this in a minimally disruptive way by inserting an explicit index for the high (or low) bin that was found, and then breaking away when no such bin is found (alias complete). There is also no reference to the "i" index looping (n-1) times, which makes the algorithm difficult to follow.

I would much prefer a cleaner, more explicit code, e.g.,

```c++
    // normalize distribution
    sum = 0.0;
    for (i=0; i<n; i++) sum += p[i];
    for (i=0; i<n; i++) p[i] /= sum;

    // sort into big and small bins
    for (i=0; i<n; i++) {
        q[i] = p[i]*n;
        if (q[i] < 1) small[nSmall++] = i;
        else big[nBig++] = i;
    }

    // aliasing
    while (nBig > 0) {
        s = small[(nSmall--)-1];
        b = big[nBig-1];
        bins[s] = b;
         q[b] = q[b] - (1-q[s]);
         if (q[b] < 1) {
             nBig--;
             small[nSmall++] = b;
         }
    }
```

**Comment by ftessier** [comment]
@rtownson can you review and try this patch, and let me know how it fares with the problematic examples you have considered? My last commit is meant to be squashed, so that this becomes a single commit to add on `develop`.

**Comment by ftessier** [comment]
I ran the problematic example `(10, 10, 1, 1)` .egsinp file to confirm that the problem is resolved.

**Comment by mchamberland** [comment]
Just chiming in to remind you of issue #24.  Does this fix also resolve #24?

**Comment by ftessier** [comment]
Wow, Issue #24!!!! Thanks for the reminder @mchamberland! Good memory. Indeed I think the proposed fix will solve that issue for the simple alias table. I am reviewing the *regular* alias table in light of this, and glancing at the code is seems it might suffer the same issue. The floating point comparison operation is not the problem here: it is only used to select whether or not to alias the bin (and this decision has an `epsilon` impact in the end). Rather, it is the "uncontrolled" loop indices which trigger extraneous aliasing when, say, either `jh` or `jl` exhaust the loop but there is no bin left to alias. Note also that the `i` index is never used per se, which makes the algorithm harder to understand (the ` i` loop ensures there is enough bin search, and relies on breaks to escape early: fragile construct).

**Comment by ftessier** [comment]
Rebases on `develop`.

**Comment by ftessier** [comment]
Updated the commits. Will leave the 4-commit trail on the side, as it is useful to understand the change history on this issue.

**Pull request merged**
