### PR TITLE
Fix #478: Fix search delimiters in medium data file.

### LINKED ISSUE #478: material data file and egspp medium sterncid parser inconsistent
I believe that the reader for material data files sees the character '.' as a terminator, where as the egspp parser (at least in egs_view and egs_chamber) can include the character '.'.  I encountered this error when I had the following two media sterncids in my material data file,
```
TISSUE_AU14.00MG
TISSUE_AU14.47G
```
Upon execution I get the following in my egslog file:
```
   Medium: TISSUE_AU14.47G
 Sterncid: TISSUE_AU14.47G
     rho:    1.01326E+00 g/cm^3
 Elements: H   C   N   O   AU
    rhoz:    9.96055E-02   1.09467E-01   2.56410E-02   7.51479E-01   1.38067E-02
      pz:    9.88179E-02   9.11378E-03   1.83062E-03   4.69692E-02   7.00894E-05
  iunrst:     0
  iaprim:     1
    gasp:    0.00000E+00 atm.
```
which is the composition of TISSUE_AU14.00MG, not TISSUE_AU14.47G.  What I should get (which I did get once I removed TISSUE_AU14.00MG from my material data file) is:
```
   Medium: TISSUE_AU14.47G
 Sterncid: TISSUE_AU14.47G
     rho:    8.84166E+00 g/cm^3
 Elements: H   C   N   O   AU
    rhoz:    6.52824E-03   7.17460E-03   1.68054E-03   4.92526E-02   9.35364E-01
      pz:    6.47662E-03   5.97328E-04   1.19981E-04   3.07840E-03   4.74835E-03
  iunrst:     0
  iaprim:     1
    gasp:    0.00000E+00 atm.
```

### PR DESCRIPTION
**Pull request by blakewalters**
Increased search delimiters from 40 to 80 chars.  This is consistent
with the length of text read in and should eliminate (most) erroneous
medium definitions when there are many blank characters in the line
containing the "MEDIUM =" key.

### CODE REVIEW

**Comment by ftessier** [comment]
Should it be changed in [`get_inputs.mortran` L223-224](https://github.com/nrc-cnrc/EGSnrc/blob/d0b1ec96473f79dfde8468fb5b5f40b2ac170931/HEN_HOUSE/src/get_inputs.mortran#L223-L224) as well?

**Comment by blakewalters** [comment]
We probably don't need to, @ftessier.  I think we keep a much tighter rein on our delimiters in the .egsinp file.  It would only be for consistency's sake.

**Comment by blakewalters** [comment]
...But I made the change anyway!

**Comment by ftessier** [comment]
Squashed the two commits together and adjusted commit title and message.

**Comment by ftessier** [comment]
Fixed a conflict when rebasing on `develop` due to the increase of the length of the TEXTPIECE string to 256 chracters on the `develop` branch in commit 0965496. There was no real conflict, but because that line is abutting the proposed changes in the current commit, git flags it as a potential conflict. All good now.

**Comment by ftessier** [comment]
Rebased on `develop`.

**Pull request merged**
