### PR TITLE
OpenMP support in EGSnrc

### PR DESCRIPTION
**Pull request by edoerner**
Modified mortran files and makefile needed to add OpenMP support in EGSnrc
**************************************************************************
    
This is a prototype for the parallelization of EGSnrc user codes using the OpenMP API. 
It is currently implemented on the DOSXYZnrc user code. An advantage of this development 
is that removes the necessity of the use of a job scheduler and/or lock-file mechanism to 
handle parallel jobs and combination of results.
    
**********************
Installation and usage
**********************
Once the included files are downloaded to $HEN_HOUSE folder follow these steps:

1. Copy the contents inside dosxyznrc folder to the user folder (i.e. $EGS_HOME/dosxyznrc).
2. In terminal, go to the dosxyznrc folder inside $EGS_HOME.
3. If the provided standard_makefile is used, just type "make omp" to compile the user code 
with OpenMP support. It essentially compiles with -fopenmp flag (for gcc only). If you want to 
use another compiler, you must change this flag with the proper one inside standard_makefile.
4. Execute the code as usual.
    
Due to the use of private variables (through the OpenMP THREADPRIVATE directive) it is needed 
for some machines to increase the stack size of the OS. For example, on macOs or 
GNU/Linux simply type on terminal "ulimit -s hard". In our case, we added that command on 
the .bashrc configuration file.
    
We have tested sources 0 (Parallel Rectangular Beam Incident from Front) and 2 (Phase-Space 
Source Incident from Any Direction), although with the notable exception of a BEAMnrc source 
mode the other sources should work without problems.
    
Also should be noted that the combination of results at the end of the simulation is 
implemented only for the *.3ddose file. Information printed on console and output to 
*.egslst file come only from the MASTER thread.

[OMP_EGS.zip](https://github.com/nrc-cnrc/EGSnrc/files/1271085/OMP_EGS.zip)

### CODE REVIEW

**Comment by ftessier** [comment]
This is great, thank you @edoerner! 🥇  I am looking forward to trying it out. I will probably close this pull request and reopen with the modifications from the attached zip archive. Unless you prefer to do it: fork the project in your github area, modify the files on your develop branch, and then submit a pull request against the EGSnrc develop branch.

**Comment by edoerner** [comment]
Hi @ftessier, thanks for the message, I will try to do the fork to check that everything is in order and then do a new pull request.

**Comment by ftessier** [comment]
Ok @edoerner I leave this pull request open as a reminder. Please close it when you submit the new one. I am looking at the changes on your fork: looks very nice and clean!

**Comment by edoerner** [comment]
Ok, I created a new pull request from my fork. So you can close this pull request. Thanks for your help!.

**Pull request closed without merging**
