### PR TITLE
Merge branch develop into master for 2021 release

### PR DESCRIPTION
**Pull request by ftessier**

### CODE REVIEW

**Comment by ftessier** [comment]
There is an issue with egs++ docs missing some files.

**Comment by mainegra** [comment]
> There is an issue with egs++ docs missing some files.

Which ones? I see the Doxygen logo missing in the bottom ...

**Comment by ftessier** [comment]
See slack. Indeed it seems the XYZ geometry was left behind. (?)

**Review by blakewalters — APPROVED** [review]

**Review by rtownson — APPROVED** [review]

**Review by mainegra — CHANGES_REQUESTED** [review]
Branch must be updated with the side branch  fix-egs++-docs.

**Review by mainegra — APPROVED** [review]

**Pull request merged**
