### PR TITLE
Add egs_mesh msh file parser

### PR DESCRIPTION
**Pull request by mxxo**
Add a basic Gmsh msh file parser for the `egs_mesh` class. The idea is to avoid requiring the `libgmsh` dependency to use `egs_mesh`. This was spun off from the original `egs_mesh` PR (#556). 

The single public API function of the msh_parser library is `EGS_Mesh parse_msh_file(std::istream& input)`, which parses an `EGS_Mesh` object from an input stream. In future PRs we will move `EGS_Mesh` to its own header and make it a subclass of `EGS_BaseGeometry` to actually run simulations. 

The parser can handle `msh` version 4.1, the latest stable format version. The format [roadmap](http://gmsh.info/doc/texinfo/gmsh.html#MSH-file-format) does not predict any changes to the sections we need. The sections `egs_mesh` uses are: 
* `$MeshFormat`: msh file format information (only v4.1 is supported)
* `$PhysicalNames`: Arbitrary group information, we are using it for EGSnrc medium names
* `$Entities`: 3D volume information and their associated `PhysicalGroups`
* `$Elements`: tetrahedrons, the volumes they belong to and constituent nodes 
* `$Nodes`: node coordinates

There is a new parser namespace `msh_parser` and a test suite file (`msh-parser-tests.cpp`).

### CODE REVIEW

**Comment by ftessier** [comment]
Relaunched the CI check (with no modification).

**Comment by ftessier** [comment]
Ok, it seems to fail compilation for "real". I will try to dump the log file on the travis output...

**Comment by ftessier** [comment]
Oh I see, I do dump the `configure.log` file at the end, but the installation hangs waiting for an aswer to `Do you want to retry? (yes/no)`. I will change that (in this pull request) to just quit the installation script upon failure, and then we should get the log...

**Comment by ftessier** [comment]
@mxxo the log is there in Travis, looks like there are issues with some mesh files. Let me know if I can adjust the compiler on the CI side, or the compiler options, to suit the mesh code.

**Comment by mxxo** [comment]
@ftessier it looks the issue is us using C++11 specific features (tuples, `auto`, etc) which we also had to change on the old PR

* https://github.com/nrc-cnrc/EGSnrc/pull/556/commits/acf765a5798a916f01e2c3d8eef214bf0d8607fc
* https://github.com/nrc-cnrc/EGSnrc/pull/556/commits/7f67c92bd77013b376edcc13118f866c10c34abc

I think every instance could be written for C++03 instead, if for some reason we wanted to avoid requiring C++11.

**Comment by rtownson** [comment]
I think it is ok to start requiring C++11 for egs++ (I already require it for compiling egs_view). It is 9 years old now, so I think not many people will be installing fresh versions of EGSnrc on systems that don't support it. If it doesn't compile we'll have to address that as a separate PR.

**Comment by mxxo** [comment]
> If it doesn't compile we'll have to address that as a separate PR.

Thank you @rtownson, do you mean I should open a new PR turning on the C++11 flags and rebase this one on it?

**Comment by rtownson** [comment]
> Thank you @rtownson, should I open a new PR turning on the C++11 flags and rebase this one on it?

I think it only needs a separate PR if turning on the C++11 flag for all of egs++ ends up requiring more than a couple trivial changes to get it to compile. Then, yes new PR and rebase on it. Otherwise, just have it as its own commit in this PR.

**Comment by mxxo** [comment]
It looks we like can build `egs++` but the script hangs on ["finalize for user"](https://travis-ci.com/github/nrc-cnrc/EGSnrc/builds/187232277#L637): 
```
Do you want to finalize for travis? (yes/no):     

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by ftessier** [comment]
I thought I had fixed this in the PR, by updating the expect script to trap
this question, no?
Amitiés,
Frédéric.

**Comment by mxxo** [comment]
@ftessier if it succeeds instead maybe it is getting stuck on the new expect line, I just took it out to see.

**Comment by mxxo** [comment]
I've just added some basic test code in `egs_mesh/tests` to start work towards an `egs_mesh` test suite.

**Comment by mxxo** [comment]
There are the beginnings of a `msh` file parser in b9d3fb2. I've been thinking about removing the dependency on `gmsh`, because we only need a very small subset of its functionality (basically just reading `msh` files).

**Comment by mxxo** [comment]
Just pushed the `$Nodes` section parser, only `$PhysicalNames` (EGSnrc media) and `$Elements` (tetrahedron data) left :)

**Comment by mxxo** [comment]
Hi @ftessier and @rtownson, I've just about finished up with the msh parser and think it is ready for review. I've reduced the scope of this PR to just landing the parser.  The primary parser function is `msh_parser::parse_msh_file`, which returns an `EGS_Mesh`. 
In subsequent PRs I will flesh out `EGS_Mesh` type and make it inherit from `EGS_BaseGeometry`.

The actual code is in `msh_parser.h` but there is also a 900-line test file `msh-parser-tests.cpp`. 
Entering egs_mesh/tests/ and running `make && ./msh-parser-tests.exe` I get: 
```text
starting test test_parse_msh_version()
test passed
starting test test_parse_msh41_entities()
test passed
starting test test_parse_msh41_node_bloc()
test passed
starting test test_parse_msh41_nodes()
test passed
starting test test_parse_msh41_groups()
test passed
starting test test_parse_msh41_element_bloc()
test passed
starting test test_parse_msh41_elements()
test passed
starting test test_parse_msh41_file_errors()
test passed
starting test test_parse_msh41_file()
test passed
9 out of 9 tests passed
```
Hopefully these rudimentary tests also work on your machines!

All of the parser functions throw exceptions (`std::runtime_error`) if parsing fails. I've noticed exceptions are
not used elsewhere in the code and can would be happy to refactor this or any other part of the code.

**Review by rtownson — APPROVED** [review]
I ran the testing code and it passed on my Windows 10 system. Note that this adds the C++11 compilation flag in the configuration script and GUI, which is fine with me. Otherwise, the additions are independent of EGSnrc so safe to add.

**Comment by ftessier** [comment]
@mxxo can I start the process of polishing up this branch to merge into `develop`, or are you still WIPping this? 😄  Even if you are still working on it, I think we should merge it: changes are secluded to the `egs_mesh` directory, so fairly safe. Except for the system-wide change to C++11, but if I read @rtownson's comment correctly, this has been tested, right?

**Comment by mxxo** [comment]
Yes, I think it is OK to merge (or at least ready for review), but about C++11: for the other user codes (applications) the extent of the testing is that they all build OK.

**Comment by rtownson** [comment]
I've been using C++11 for a while and I haven't noticed any problems.

**Comment by ftessier** [comment]
Super. I will merge this in `develop`. (I will perhaps make a separate PR for the change to c++11)

**Comment by mxxo** [comment]
Maybe we could jump to C++14 if that's the case? Mostly a bugfix release for C++11 but lots of nice quality of life improvements too :)

**Comment by ftessier** [comment]
Yes, why not? Good idea. I will extract the `--std=c++11` from this PR, and open a new one just for that.

**Comment by ftessier** [comment]
@mxxo may I `--force-push` to this PR branch (i.e. modify its history to reword, squash, rebase, etc.)? I would like to polish it up before merging.

**Comment by mxxo** [comment]
Sure thing! Thanks!

**Comment by ftessier** [comment]
Rebased on current `develop` (Release 2021). Checked that there are no relative diffs with the original `mxxo/mesh-geometry` branch after the rebase (for the files that were modified by this PR). For the record, I used the following command to check that (fish shell):

```fish
for file in (git diff (git merge-base mxxo/mesh-geometry develop) mxxo/mesh-geometry --name-only)
    git mesh-geometry mxxo/mesh-geometry $file
end
```

This returns an empty diff set.

**Comment by ftessier** [comment]
Rebased on the `feature-cc14` branch to re-introduce the update to the C++14 standard. Let's see if this compiles without issue on Travis! Checked again with the same `git diff` trick that the only changes this rebase introduced are the three changes from `-std=c++11` to `-std=c++14`.

**Comment by ftessier** [comment]
Rebased on develop for Release 2022.

**Pull request closed without merging**
