### PR TITLE
Geometry libraries for cubic and hexagonal lattice in egsnrc

### PR DESCRIPTION
**Pull request by MartinMartinov**
Add lattice geometries to the egs++ geometry distribution in either the hexagonal close-packed or cubic lattice configurations.  These lattice geometries take in two geometries, and embeds one of them into a chosen region of the other for a chosen number density.  The geometry recursed to form the lattice only has one set of regions repeated everywhere, hence embedded geometries cannot be distinguished.

### CODE REVIEW

**Comment by ftessier** [comment]
Thanks you @MartinMartinov, will review as we gear up next week for the 2019 release!

**Comment by rtownson** [comment]
Hi @MartinMartinov, could you add a couple geometry examples, like the ones in HEN_HOUSE/egs++/geometry/examples? I figure you have something practical on hand that might be helpful to share.

**Comment by MartinMartinov** [comment]
Hi @rtownson, because this geometry was built in a very depricated version of EGSnrc (~2017), I'm actually in the process of rebuilding it for the current develop branch version.  Additionally, I'm actually properly linking it to egs_gtransformed (as opposed to creating a copy/paste clone of it for the library), implementing labelling and B-scaling (or trying to at least), combing the cubic and hexagonal lattice into a single library, adding a Bravais lattice option to that library, and re-implementing the hownear for efficiency.

Once I have egs_lattice built and tested I'll definitely toss in an example file with all available options in the new pull request.  On that note, you can probably close this pull request if you'd like.

**Comment by rtownson** [comment]
Great to hear @MartinMartinov! I'll leave the PR here as a reminder and to signal to users that this is something in the works. Once you submit a new PR, I'll close this one :)

**Comment by ftessier** [comment]
@MartinMartinov @rtownson  can we close this pull request now, given #561 ?

**Comment by MartinMartinov** [comment]
I see no reason not too.

**Pull request closed without merging**
