### PR TITLE
Fix #393: Fix dimension check for quarter isocentre leaves

### LINKED ISSUE #393: Wrong check on input dimension of quarter iso leaves for SYNCHDMLC?
It seems to me like [this line](https://github.com/nrc-cnrc/EGSnrc/blob/develop/HEN_HOUSE/omega/beamnrc/CMs/SYNCHDMLC_cm.mortran#L1784) should be
``
IF(ZGROOVE_$SYNCHDMLC(5)<ZTONGUE_$SYNCHDMLC(5))[
``
instead of the current
``
IF(ZGROOVE_$SYNCHDMLC(5)>ZTONGUE_$SYNCHDMLC(5))[
``

If quarter leaves are treated identically to half leaves. The error message for the failed check also indicates that ZGROOVE < ZTONGUE is the intended check instead of ZGROOVE > ZTONGUE.

See [this line](https://github.com/nrc-cnrc/EGSnrc/blob/develop/HEN_HOUSE/omega/beamnrc/CMs/SYNCHDMLC_cm.mortran#L1554) for the dimension check of half iso leaves

### PR DESCRIPTION
**Pull request by blakewalters**
Previously, the code exited with an error message if ZTONGUE was greater than 
ZGROOVE for quarter isocentre leaves.  Confusingly, the output message
stated that the code was exiting because ZTONGUE<ZGROOVE. Ultimately, it
was determined that the output message was correct and the check should
be on ZTONGUE<ZGROOVE.  Bug found by Marc-Andre Renaud.  Fixed with info
provided by Emily Heath and Tony Popescu.

### CODE REVIEW

**Comment by blakewalters** [comment]
Good thought @marenaud.  I'll go through HOWFAR and make sure that a more fundamental change isn't also required.  This will also determine whether it's possible to have a WARNING instead of an ERROR message.  In the meantime, please keep this pull request open!

**Comment by mchamberland** [comment]
I didn't find the bug! Marc-André Renaud (@marenaud) did!

**Comment by blakewalters** [comment]
Oops.  See amended message above.  There are also more changes required in HOWFAR and HOWNEAR.

**Comment by blakewalters** [comment]
Hi guys:  Please don't merge this fix until it's been determined whether ZTONGUE > ZGROOVE or ZTONGUE < ZGROOVE for quarter isocentre leaves.  At this point, we suspect that merely the output message for the error check and the figure in the BEAMnrc Manual are incorrect, but we're waiting for feedback from Varian.  Thanks!

**Comment by ojalaj** [comment]
Hi all. I've got a confirmation from Varian that zt < zg and the figure in proprietary data package is correct. Hopefully you get the same answer :) !

**Comment by blakewalters** [comment]
Okay, I think this pull request is ready to merge.  Based on multiple user input, I've gone back to the original requirement that ZGROOVE < ZTONGUE for quarter isocentre leaves and changed the output error message to be consistent with this as well as the figure and example input in the BEAMnrc manual.

**Comment by ftessier** [comment]
Squashed the two commits and adjusted the commit message accordingly.

**Comment by ftessier** [comment]
@blakewalters the changes in `SYNCHDMLC_cm.mortran` between lines 1181 and 1200 don't seem substantial (alignment only). Can I revert these changes here to avoid confusion?

**Comment by blakewalters** [comment]
No @ftessier.  There were extra spaces here that caused Mortran errors during compilation.

**Pull request merged**
