### PR TITLE
Check maximum source energy against production threshold UE, UP

### PR DESCRIPTION
**Pull request by blakewalters**
Addresses issue #634

### CODE REVIEW

**Comment by blakewalters** [comment]
@mainegra, @ftessier, @rtownson: Here's a check to address the bug that @dworogers found when trying to run with Ekmax > UE, UP.  Perhaps a bit overengineered, but it should do the trick.

**Review by ftessier — APPROVED** [review]
Sounds good!

**Comment by mainegra** [comment]
@blakewalters thanks for looking into this! 
There is only one issue with the `mono=0` case: Here one can enter one or more individual energy values and they _must not be in increasing order_, although most of the time people will enter individual energy values in an ordered manner. Hence we must check for the maximum energy during the input loop over all energies found in `subroutine source` in the block between lines 1471 and 1474.

**Comment by blakewalters** [comment]
I hadn't accounted for that option with mono=0, @mainegra.  Good catch!  Look forward to another commit.

**Comment by blakewalters** [comment]
Okay, @mainegra, @rtownson and @ftessier: I think I've now accounted for the option to input multiple energies under the mono-energy option.  Please take a look & approve or disapprove when you get the chance.

**Review by mainegra — APPROVED** [review]

**Review by rtownson — APPROVED** [review]

**Comment by ftessier** [comment]
This pull request was closed automatically upon merging the target branch #598 `feature-g-update` into `develop`. I did not realize that this was the target of another PR. I have reinstated the branch and I am reopening this PR.

**Pull request merged**
