### PR TITLE
Add the dirt density file used by icrm-hpge-example

### PR DESCRIPTION
**Pull request by rtownson**
Add the dirt density correction file that was used in the icrm-hpge MC comparison. Also update the materials in the example input file to refer to the correctly named density files.

### CODE REVIEW

**Review by mainegra — APPROVED** [review]

**Comment by ftessier** [comment]
@rtownson I don't understand why this material is called `dirt`, if it is only `Si` and `O`. I presume it was the name used in the ICRM comparison, but the generic `dirt` seems misleading out of context. Thoughts?

**Comment by rtownson** [comment]
You're right, I'll rename it to silicondioxide.density.

**Review by ftessier — APPROVED** [review]

**Comment by ftessier** [comment]
@blakewalters please review when you have a chance.

**Comment by ftessier** [comment]
@blakewalters please review this one when you have a minute.

**Comment by ftessier** [comment]
Rebased on develop.

**Review by blakewalters — APPROVED** [review]

**Comment by ftessier** [comment]
Squashed the commits.

**Pull request merged**
