### PR TITLE
Implement user-defined boundary tolerance in geometry objects

### PR DESCRIPTION
**Pull request by mchamberland**
This is an attempt at resolving issue #86. Feel free to simply close if you'd prefer using a different approach than I did.

My goal in this pull request is to have a user-defined `boundaryTolerance` variable that is used to check for floating point errors in geometries. The `boundaryTolerance` variable is a protected member of `EGS_BaseGeometry` and has a default value of 1e-10. Being non-static, this allows the user to set a different value of `boundaryTolerance` in any geometry. The tolerance can be set with the input key `boundary tolerance`.

`EGS_StackGeometry` already has a `tolerance` variable that serves the same purpose. For backwards compatibility, the `tolerance` key is preserved and simply duplicates the functionality of the `boundary tolerance` key.

### CODE REVIEW

**Comment by mchamberland** [comment]
There are a few instances I did not change because the current hard-coded values are very high (1e-2). I wasn't sure if there was any special reason for such high values. If you think it's safe, I'll change them to `boundaryTolerance`. The specific instances are in

egs_cylinders.h: lines [286](https://github.com/mchamberland/EGSnrc/blob/8d5e6857b7cf5b61c8274f75a97caf5fe5530d89/HEN_HOUSE/egs%2B%2B/geometry/egs_cylinders/egs_cylinders.h#L286), [294](https://github.com/mchamberland/EGSnrc/blob/8d5e6857b7cf5b61c8274f75a97caf5fe5530d89/HEN_HOUSE/egs%2B%2B/geometry/egs_cylinders/egs_cylinders.h#L294), [338](https://github.com/mchamberland/EGSnrc/blob/8d5e6857b7cf5b61c8274f75a97caf5fe5530d89/HEN_HOUSE/egs%2B%2B/geometry/egs_cylinders/egs_cylinders.h#L338), [353](https://github.com/mchamberland/EGSnrc/blob/8d5e6857b7cf5b61c8274f75a97caf5fe5530d89/HEN_HOUSE/egs%2B%2B/geometry/egs_cylinders/egs_cylinders.h#L353), and [372](https://github.com/mchamberland/EGSnrc/blob/8d5e6857b7cf5b61c8274f75a97caf5fe5530d89/HEN_HOUSE/egs%2B%2B/geometry/egs_cylinders/egs_cylinders.h#L372).

egs_spheres.h: line [183](https://github.com/mchamberland/EGSnrc/blob/8d5e6857b7cf5b61c8274f75a97caf5fe5530d89/HEN_HOUSE/egs%2B%2B/geometry/egs_spheres/egs_spheres.cpp#L183)

**Comment by ftessier** [comment]
Very nice @mchamberland, this is much more consistent. There are a few hard-coded 1e-10 values remaining `egs_prism`, `egs_pyramids`, and `egs_nd_geometry`. Is this intentional?

**Comment by mchamberland** [comment]
Yes, I meant to ask about those. My compiler was complaining about accessing a protected member (`boundaryTolerance`) in a static function. I'm not sure how to workaround that.

Also, all those hard-coded 1e-10 are inside the functions that create the geometry object, not in `howfar` (or related functions).

**Comment by rtownson** [comment]
These changes were included in pull request #177.

**Pull request closed without merging**
